### ISSUE TITLE
Release tracking issue

### ISSUE THREAD

**Issue by case** [domainr/domainr-mac#18]
@connor: 
- [x] #2 preferences menu
- [x] #19 "Powered by Domai.nr" in the dropdown
- [x] green dots should match size of dots on website (e.g. [mac app](http://cl.ly/image/2X2R1j3e2I0T) vs. [site](http://cl.ly/image/2j3t0h3V053p))
- [x] set OS X min-version to 10.7
- [x] google analytics tasks
- [x] build out prefs window
  - [x] keyboard shortcut recorder
  - [x] toggle for blackwhite/color icons
- [ ] UI polish
  - [ ] better icon (see #20)
  - [ ] align colors/fonts w/ website
  - [ ] align spacing

@case:
- [ ] App Store misc
- [ ] launch marketing misc

**Comment by connor** [comment]
Let's ship this thing.

@case you game? I can polish this up over the next 5-7 days and get ready to :ship:.
